//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPLKCORE.Form.PensionTransaction {
    
    
    public partial class AdminSuspense {
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// ClientTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabContainer ClientTabs;
        
        /// <summary>
        /// TabPanelSuspenseRequest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel TabPanelSuspenseRequest;
        
        /// <summary>
        /// UCSuspenseRequest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DPLKCORE.Form.PensionTransaction.UserControl.AdminSuspense.SuspenseRequest UCSuspenseRequest;
        
        /// <summary>
        /// TabPanelSuspenseApproval control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel TabPanelSuspenseApproval;
        
        /// <summary>
        /// UCSuspenseApproval control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DPLKCORE.Form.PensionTransaction.UserControl.AdminSuspense.SuspenseApproval UCSuspenseApproval;
        
        /// <summary>
        /// TabPanelSuspenseReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel TabPanelSuspenseReport;
        
        /// <summary>
        /// UCSuspenseReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DPLKCORE.Form.PensionTransaction.UserControl.AdminSuspense.SuspenseReport UCSuspenseReport;
    }
}
